### ISSUE TITLE
Is there a way to use pipes without evaluating lhs?

### ISSUE THREAD

**Issue by rpruim** [tidyverse/magrittr#148] opened 2017-05-29 23:11 UTC
I'd like to do something like

```{r}
<something with randomness> %>% repeat_n(1000)
```
To create a randomization or bootstrap distribution.  Currently, it seems that I just get 1000 copies of the same thing because the lhs gets evaluated too soon.

So I mocked up a new operator to see how hard it would be to evaluate in a different way.  Clearly, `magrittr` is doing a lot of extra stuff (much of it in functions that are not exported).  But it there are fundamental reason why an approach like the one below can't be used?

```{r}
`%>>%` <-
function (lhs, rhs)
{
  qlhs <- rlang::enquo(lhs)
  qrhs <- rlang::enquo(rhs)
  n  <- length(qrhs[[2]])
  if (n > 1) {
    for (i in n:2L) {
      qrhs[[2]][[i+1]] <- qrhs[[2]][[i]]
    }
  }
  qrhs[[2]][[2]] <- qlhs[[2]]
  rlang::eval_tidy(qrhs)
}
```

**Comment by stefanbache** [comment] 2017-05-30 00:08
The design choice is that `%>%` is eager. One reason is that it may be used several places on the rhs and should therefore not be an expression to be evaluated, but a value. Therefore, `%>%`, should not be used with this kind of NS ideas.

**Comment by rpruim** [comment] 2017-05-30 00:38
What if there were some way for rhs to have access to the unevaluated lhs *in addition*?  Functions that did not use this feature would behave as now, but new functions could be written to things like the example I suggested.

**Comment by smbache** [comment] 2017-05-30 00:46
Personally, I'm not too comfortable with this and would prefer to keep it simple, and as transparent as possible. I get that there are some cases where there is a desire to use the pipe in a non-standard way, but I don't think it is worth it.

**Comment by hadley** [comment] 2018-07-02 20:16
Duplicate of #120.

I am attempting to persuade @smbache that laziness is a useful property to have. We'll see if I succeed 😄

**Closed by hadley** 2018-07-02 20:16 UTC
